name: Release Docker image
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  release:
    name: Build and release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: debian
            platforms: linux/amd64, linux/386
          - os: alpine
            platforms: linux/amd64
          - os: scratch
            platforms: linux/amd64
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: get version
        run: echo "LATEST_VERSION=$(curl -s 'https://api.github.com/repos/versatiles-org/versatiles-rs/releases/latest' | jq -r '.tag_name')" >> $GITHUB_ENV
      - name: "Build and push"
        uses: docker/build-push-action@v4
        with:
          platforms: ${{ matrix.platforms }}
          file: "docker/${{ matrix.os }}.Dockerfile"
          push: true
          tags: versatiles/versatiles:latest-${{ matrix.os }}, versatiles/versatiles:${{ env.LATEST_VERSION }}-${{ matrix.os }}
